name: ClickUp to Intercom Sync

on:
  schedule:
    - cron: '0 3 * * *'  # Каждый день в 6:00 MSK
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run sync script
      env:
        CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
        CLICKUP_TEAM_ID: ${{ secrets.CLICKUP_TEAM_ID }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        INTERCOM_ACCESS_TOKEN: ${{ secrets.INTERCOM_ACCESS_TOKEN }}
        INTERCOM_OWNER_ID: ${{ secrets.INTERCOM_OWNER_ID }}
        INTERCOM_AUTHOR_ID: ${{ secrets.INTERCOM_AUTHOR_ID }}
        INTERCOM_REGION: ${{ secrets.INTERCOM_REGION }}
        INTERCOM_VERSION: ${{ secrets.INTERCOM_VERSION }}
        CLICKUP_ONLY_OPEN: ${{ secrets.CLICKUP_ONLY_OPEN }}
        CLICKUP_UPDATED_LOOKBACK_HOURS: ${{ secrets.CLICKUP_UPDATED_LOOKBACK_HOURS }}
        SYNC_STATE_FILE: ${{ secrets.SYNC_STATE_FILE }}
        DRY_RUN: ${{ secrets.DRY_RUN }}
        FETCH_ALL: ${{ secrets.FETCH_ALL }}
      run: python synch.py
